version: '3.8'


services:
    # app_file_sharing:
    #     restart: always
    #     tty: true
    #     build: ./app_file_sharing
    #     privileged: true
    #     volumes:
    #         - ./app_file_sharing:/app_file_sharing
    #         - ./app_file_sharing/postgres-data:/app_file_sharing/postgres-data
    #         - ./supervisord-logs/app_file_sharing:/var/log/supervisor
    #     networks:
    #         - apps_network

    # app_chatgpt:
    #     restart: always
    #     tty: true
    #     build: ./app_chatgpt
    #     privileged: true
    #     volumes:
    #         - ./app_chatgpt:/app_chatgpt
    #         - ./app_chatgpt/postgres-data:/app_chatgpt/postgres-data
    #         - ./supervisord-logs/app_chatgpt:/var/log/supervisor
    #     networks:
    #         - apps_network

    reverse_proxy:
        build: 
            context: ./reverse_nginx_proxy
            target: dev
        container_name: reverse_proxy
        ports:
            - 80:80
            - 443:443
        networks:
            - apps_network

networks:
    apps_network:
        driver: bridge